/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liubz_androidtea_utils_NdkUtils */

#ifndef _Included_com_liubz_androidtea_utils_NdkUtils
#define _Included_com_liubz_androidtea_utils_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liubz_androidtea_utils_NdkUtils
 * Method:    getStringFromNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liubz_androidtea_utils_NdkUtils_getStringFromNdk
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
